   - name: Generate GitHub Stats
  uses: anuraghazra/github-readme-stats@latest # Replace 'v2' with 'latest' or another valid version
  with:
    username: sansatid
    hide: kotlin,java,vue,llvm
    layout: compact
    theme: transparent
    hide_border: true
    count_private: true
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      # เพิ่มขั้นตอนนี้เข้าไปที่นี่
      - name: Get Repo Language Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/sansatid/your-repo-languages
