name: Update README with top languages

on:
  schedule:
    - cron: "0 */6 * * *" # รันทุก 6 ชั่วโมง
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate top langs SVG
      run: |
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        "https://github-readme-stats.vercel.app/api/top-langs/?username=sansatid&count_private=true&layout=compact&theme=transparent&hide_border=true" \
        -o top-langs.svg

    - name: Commit and push if changed
      run: |
        git config --global user.email "changsansatid@gmail.com"
        git config --global user.name "sansatid"
        git add top-langs.svg
        git commit -m "Update top languages" || echo "No changes"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/sansatid/sansatid.git
