name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate README stats
        uses: yassinebridi/readme-stats-action@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          user: sansatid
          hide: kotlin,java,vue,llvm
          layout: compact
          theme: transparent
          hide_border: true
          count_private: true

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "chore: update README with stats" || echo "No changes to commit"
          git push
