name: Update README

on:
  schedule:
    - cron: "0 * * * *" # ทุกชั่วโมง
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
  uses: anuraghazra/github-readme-stats@v2
  with:
    username: sansatid
    hide: kotlin,java,vue,llvm
    layout: compact
    theme: transparent
    hide_border: true
    count_private: true
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      # เพิ่มขั้นตอนนี้เข้าไปที่นี่
      - name: Get Repo Language Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/sansatid/your-repo-languages
